### PR TITLE
Publish module to drupal.org

### PR DESCRIPTION
**Pull request by suryanto**
I created composer.json file, I also removed lib folder and added it as composer dependency.

### CODE REVIEW

**Comment by aalexanderkevin** [comment]
Thank you for your contributions.

However, for security, confidentiality and to ensure further maintenance reasons, we may need to reupload to drupal.org with our own official account.

**Comment by suryanto** [comment]
I can give you access as module maintainer on drupal.org. Can you tell me your drupal account name?

**Comment by rizdaprasetya** [comment]
Hi @suryanto thanks for the contribution, and making it easier for more Drupal users to accept payment, we appreciate community contribution 👍 

However it is not possible for us to be invited under your Drupal account and treat it as official. Since our Security & Compliance team security best practice advise us not to allow 3rd party to have write access to an official repo (unless you revoke the write access of your own account, which we don't think is a good idea).

We also reviewed that the https://www.drupal.org/project/commerce_midtrans contains donation link to your account. And the [commit history](https://git.drupalcode.org/project/commerce_midtrans/commits/) does not reflect the commit history from this Github repo, hence we cannot fully ensure the code integrity.

So it's best for us to create our own official account sometime in the future. Without disturbing your own.

For now we'll recognize your Drupal.org version of the module as "community contribution" (and please add statement on the description to indicate that is "community contribution" or un-official).
Also we may list it on our [docs](https://docs.midtrans.com) as community recognition. Feel free to continue contributing even more 😃

**Comment by suryanto** [comment]
Hi @rizdaprasetya 

I just added disclaimer on drupal module page.

Disclaimer: This module is a community contribution. It is an unofficial version of Midtrans payment gateway for drupal.

**Comment by rizdaprasetya** [comment]
Great, thanks!

**Pull request merged**
